/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.test;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1100680691;

	/**
	 * The singleton instance of <code>test</code>
	 */
	public static final Test TEST = new Test();

	/**
	 * No further instances allowed
	 */
	private Test() {
		super("test");
	}
}
