/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentTransaction extends org.jooq.impl.TableImpl<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord> {

	private static final long serialVersionUID = 1969733338;

	/**
	 * The singleton instance of <code>team3.PAYMENT_TRANSACTION</code>
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction PAYMENT_TRANSACTION = new edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord> getRecordType() {
		return edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord.class;
	}

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.id</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.uid</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> UID = createField("uid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.date</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.Integer> DATE = createField("date", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.method</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> METHOD = createField("method", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.description</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.user</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.reason</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.comments</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.PAYMENT_TRANSACTION.status</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>team3.PAYMENT_TRANSACTION</code> table reference
	 */
	public PaymentTransaction() {
		super("PAYMENT_TRANSACTION", edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3);
	}

	/**
	 * Create an aliased <code>team3.PAYMENT_TRANSACTION</code> table reference
	 */
	public PaymentTransaction(java.lang.String alias) {
		super(alias, edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3, edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.Integer> getIdentity() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.IDENTITY_PAYMENT_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord> getPrimaryKey() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.KEY_PAYMENT_TRANSACTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord>>asList(edu.uga.csci4050.group3.jooq.team3.Keys.KEY_PAYMENT_TRANSACTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction as(java.lang.String alias) {
		return new edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction(alias);
	}
}
