/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalLocation extends org.jooq.impl.TableImpl<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord> {

	private static final long serialVersionUID = 1018944360;

	/**
	 * The singleton instance of <code>team3.RENTAL_LOCATION</code>
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation RENTAL_LOCATION = new edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord> getRecordType() {
		return edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord.class;
	}

	/**
	 * The column <code>team3.RENTAL_LOCATION.id</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.uid</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> UID = createField("uid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.name</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.street_address</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> STREET_ADDRESS = createField("street_address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.state</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.country</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.zipcode</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> ZIPCODE = createField("zipcode", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.city</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.RENTAL_LOCATION.capacity</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> CAPACITY = createField("capacity", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>team3.RENTAL_LOCATION</code> table reference
	 */
	public RentalLocation() {
		super("RENTAL_LOCATION", edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3);
	}

	/**
	 * Create an aliased <code>team3.RENTAL_LOCATION</code> table reference
	 */
	public RentalLocation(java.lang.String alias) {
		super(alias, edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3, edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> getIdentity() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.IDENTITY_RENTAL_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord> getPrimaryKey() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.KEY_RENTAL_LOCATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord>>asList(edu.uga.csci4050.group3.jooq.team3.Keys.KEY_RENTAL_LOCATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation as(java.lang.String alias) {
		return new edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation(alias);
	}
}
