/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleType extends org.jooq.impl.TableImpl<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord> {

	private static final long serialVersionUID = 1992205928;

	/**
	 * The singleton instance of <code>team3.VEHICLE_TYPE</code>
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.VehicleType VEHICLE_TYPE = new edu.uga.csci4050.group3.jooq.team3.tables.VehicleType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord> getRecordType() {
		return edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord.class;
	}

	/**
	 * The column <code>team3.VEHICLE_TYPE.id</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>team3.VEHICLE_TYPE.uid</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.String> UID = createField("uid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.VEHICLE_TYPE.name</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>team3.VEHICLE_TYPE.hourly_rate</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Double> HOURLY_RATE = createField("hourly_rate", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>team3.VEHICLE_TYPE.daily_rate</code>. 
	 */
	public final org.jooq.TableField<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Double> DAILY_RATE = createField("daily_rate", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * Create a <code>team3.VEHICLE_TYPE</code> table reference
	 */
	public VehicleType() {
		super("VEHICLE_TYPE", edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3);
	}

	/**
	 * Create an aliased <code>team3.VEHICLE_TYPE</code> table reference
	 */
	public VehicleType(java.lang.String alias) {
		super(alias, edu.uga.csci4050.group3.jooq.team3.Team3.TEAM3, edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Integer> getIdentity() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.IDENTITY_VEHICLE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord> getPrimaryKey() {
		return edu.uga.csci4050.group3.jooq.team3.Keys.KEY_VEHICLE_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord>>asList(edu.uga.csci4050.group3.jooq.team3.Keys.KEY_VEHICLE_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public edu.uga.csci4050.group3.jooq.team3.tables.VehicleType as(java.lang.String alias) {
		return new edu.uga.csci4050.group3.jooq.team3.tables.VehicleType(alias);
	}
}
