/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>team3</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.Integer> IDENTITY_PAYMENT_TRANSACTION = Identities0.IDENTITY_PAYMENT_TRANSACTION;
	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> IDENTITY_RENTAL_LOCATION = Identities0.IDENTITY_RENTAL_LOCATION;
	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalTransactionRecord, java.lang.Integer> IDENTITY_RENTAL_TRANSACTION = Identities0.IDENTITY_RENTAL_TRANSACTION;
	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleRecord, java.lang.Integer> IDENTITY_VEHICLE = Identities0.IDENTITY_VEHICLE;
	public static final org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Integer> IDENTITY_VEHICLE_TYPE = Identities0.IDENTITY_VEHICLE_TYPE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord> KEY_PAYMENT_TRANSACTION_PRIMARY = UniqueKeys0.KEY_PAYMENT_TRANSACTION_PRIMARY;
	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord> KEY_RENTAL_LOCATION_PRIMARY = UniqueKeys0.KEY_RENTAL_LOCATION_PRIMARY;
	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalTransactionRecord> KEY_RENTAL_TRANSACTION_PRIMARY = UniqueKeys0.KEY_RENTAL_TRANSACTION_PRIMARY;
	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleRecord> KEY_VEHICLE_PRIMARY = UniqueKeys0.KEY_VEHICLE_PRIMARY;
	public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord> KEY_VEHICLE_TYPE_PRIMARY = UniqueKeys0.KEY_VEHICLE_TYPE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord, java.lang.Integer> IDENTITY_PAYMENT_TRANSACTION = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION, edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION.ID);
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord, java.lang.Integer> IDENTITY_RENTAL_LOCATION = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION, edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION.ID);
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalTransactionRecord, java.lang.Integer> IDENTITY_RENTAL_TRANSACTION = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION, edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION.ID);
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.User.USER, edu.uga.csci4050.group3.jooq.team3.tables.User.USER.ID);
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleRecord, java.lang.Integer> IDENTITY_VEHICLE = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE, edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE.ID);
		public static org.jooq.Identity<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord, java.lang.Integer> IDENTITY_VEHICLE_TYPE = createIdentity(edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE, edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.PaymentTransactionRecord> KEY_PAYMENT_TRANSACTION_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION, edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION.ID);
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalLocationRecord> KEY_RENTAL_LOCATION_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION, edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION.ID);
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.RentalTransactionRecord> KEY_RENTAL_TRANSACTION_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION, edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION.ID);
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.User.USER, edu.uga.csci4050.group3.jooq.team3.tables.User.USER.ID);
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleRecord> KEY_VEHICLE_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE, edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE.ID);
		public static final org.jooq.UniqueKey<edu.uga.csci4050.group3.jooq.team3.tables.records.VehicleTypeRecord> KEY_VEHICLE_TYPE_PRIMARY = createUniqueKey(edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE, edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE.ID);
	}
}
