/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in team3
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table team3.PAYMENT_TRANSACTION
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction PAYMENT_TRANSACTION = edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION;

	/**
	 * The table team3.RENTAL_LOCATION
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation RENTAL_LOCATION = edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION;

	/**
	 * The table team3.RENTAL_TRANSACTION
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction RENTAL_TRANSACTION = edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION;

	/**
	 * The table team3.USER
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.User USER = edu.uga.csci4050.group3.jooq.team3.tables.User.USER;

	/**
	 * The table team3.VEHICLE
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.Vehicle VEHICLE = edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE;

	/**
	 * The table team3.VEHICLE_TYPE
	 */
	public static final edu.uga.csci4050.group3.jooq.team3.tables.VehicleType VEHICLE_TYPE = edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE;
}
