/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.team3;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team3 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -970990948;

	/**
	 * The singleton instance of <code>team3</code>
	 */
	public static final Team3 TEAM3 = new Team3();

	/**
	 * No further instances allowed
	 */
	private Team3() {
		super("team3");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			edu.uga.csci4050.group3.jooq.team3.tables.PaymentTransaction.PAYMENT_TRANSACTION,
			edu.uga.csci4050.group3.jooq.team3.tables.RentalLocation.RENTAL_LOCATION,
			edu.uga.csci4050.group3.jooq.team3.tables.RentalTransaction.RENTAL_TRANSACTION,
			edu.uga.csci4050.group3.jooq.team3.tables.User.USER,
			edu.uga.csci4050.group3.jooq.team3.tables.Vehicle.VEHICLE,
			edu.uga.csci4050.group3.jooq.team3.tables.VehicleType.VEHICLE_TYPE);
	}
}
