/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rentalservice extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -443856081;

	/**
	 * The singleton instance of <code>rentalservice</code>
	 */
	public static final Rentalservice RENTALSERVICE = new Rentalservice();

	/**
	 * No further instances allowed
	 */
	private Rentalservice() {
		super("rentalservice");
	}
}
