/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rentalservice extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -2128018062;

	/**
	 * The singleton instance of <code>rentalservice</code>
	 */
	public static final Rentalservice RENTALSERVICE = new Rentalservice();

	/**
	 * No further instances allowed
	 */
	private Rentalservice() {
		super("rentalservice");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			edu.uga.csci4050.group3.jooq.rentalservice.tables.PaymentTransaction.PAYMENT_TRANSACTION,
			edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalLocation.RENTAL_LOCATION,
			edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION,
			edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER,
			edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE,
			edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE);
	}
}
