/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalTransactionRecord extends org.jooq.impl.UpdatableRecordImpl<edu.uga.csci4050.group3.jooq.rentalservice.tables.records.RentalTransactionRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -394675570;

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.uid</code>. 
	 */
	public void setUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.uid</code>. 
	 */
	public java.lang.String getUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.start_date</code>. 
	 */
	public void setStartDate(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.start_date</code>. 
	 */
	public java.lang.Short getStartDate() {
		return (java.lang.Short) getValue(2);
	}

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.end_date</code>. 
	 */
	public void setEndDate(java.lang.Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.end_date</code>. 
	 */
	public java.lang.Short getEndDate() {
		return (java.lang.Short) getValue(3);
	}

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.user</code>. 
	 */
	public void setUser(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.user</code>. 
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>rentalservice.RENTAL_TRANSACTION.vehicle</code>. 
	 */
	public void setVehicle(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rentalservice.RENTAL_TRANSACTION.vehicle</code>. 
	 */
	public java.lang.String getVehicle() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field4() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION.VEHICLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value4() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getVehicle();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RentalTransactionRecord
	 */
	public RentalTransactionRecord() {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION);
	}

	/**
	 * Create a detached, initialised RentalTransactionRecord
	 */
	public RentalTransactionRecord(java.lang.Integer id, java.lang.String uid, java.lang.Short startDate, java.lang.Short endDate, java.lang.String user, java.lang.String vehicle) {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.RentalTransaction.RENTAL_TRANSACTION);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, startDate);
		setValue(3, endDate);
		setValue(4, user);
		setValue(5, vehicle);
	}
}
