/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<edu.uga.csci4050.group3.jooq.rentalservice.tables.records.UserRecord> implements org.jooq.Record15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1715909147;

	/**
	 * Setter for <code>rentalservice.USER.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rentalservice.USER.uid</code>. 
	 */
	public void setUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.uid</code>. 
	 */
	public java.lang.String getUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rentalservice.USER.username</code>. 
	 */
	public void setUsername(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.username</code>. 
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rentalservice.USER.password</code>. 
	 */
	public void setPassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.password</code>. 
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>rentalservice.USER.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>rentalservice.USER.first_name</code>. 
	 */
	public void setFirstName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.first_name</code>. 
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>rentalservice.USER.last_name</code>. 
	 */
	public void setLastName(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.last_name</code>. 
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>rentalservice.USER.role</code>. 
	 */
	public void setRole(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.role</code>. 
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>rentalservice.USER.license</code>. 
	 */
	public void setLicense(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.license</code>. 
	 */
	public java.lang.String getLicense() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>rentalservice.USER.dateofbirth</code>. 
	 */
	public void setDateofbirth(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.dateofbirth</code>. 
	 */
	public java.lang.Integer getDateofbirth() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>rentalservice.USER.street_address</code>. 
	 */
	public void setStreetAddress(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.street_address</code>. 
	 */
	public java.lang.String getStreetAddress() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>rentalservice.USER.state</code>. 
	 */
	public void setState(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.state</code>. 
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>rentalservice.USER.country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>rentalservice.USER.zipcode</code>. 
	 */
	public void setZipcode(java.lang.Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.zipcode</code>. 
	 */
	public java.lang.Integer getZipcode() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>rentalservice.USER.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>rentalservice.USER.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.LICENSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.DATEOFBIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.STREET_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field14() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.ZIPCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getLicense();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getDateofbirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getStreetAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value14() {
		return getZipcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getCity();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Integer id, java.lang.String uid, java.lang.String username, java.lang.String password, java.lang.String email, java.lang.String firstName, java.lang.String lastName, java.lang.String role, java.lang.String license, java.lang.Integer dateofbirth, java.lang.String streetAddress, java.lang.String state, java.lang.String country, java.lang.Integer zipcode, java.lang.String city) {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.User.USER);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, username);
		setValue(3, password);
		setValue(4, email);
		setValue(5, firstName);
		setValue(6, lastName);
		setValue(7, role);
		setValue(8, license);
		setValue(9, dateofbirth);
		setValue(10, streetAddress);
		setValue(11, state);
		setValue(12, country);
		setValue(13, zipcode);
		setValue(14, city);
	}
}
