/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleTypeRecord extends org.jooq.impl.UpdatableRecordImpl<edu.uga.csci4050.group3.jooq.rentalservice.tables.records.VehicleTypeRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double> {

	private static final long serialVersionUID = 897598265;

	/**
	 * Setter for <code>rentalservice.VEHICLE_TYPE.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE_TYPE.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE_TYPE.uid</code>. 
	 */
	public void setUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE_TYPE.uid</code>. 
	 */
	public java.lang.String getUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE_TYPE.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE_TYPE.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE_TYPE.hourly_rate</code>. 
	 */
	public void setHourlyRate(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE_TYPE.hourly_rate</code>. 
	 */
	public java.lang.Double getHourlyRate() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE_TYPE.daily_rate</code>. 
	 */
	public void setDailyRate(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE_TYPE.daily_rate</code>. 
	 */
	public java.lang.Double getDailyRate() {
		return (java.lang.Double) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE.HOURLY_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE.DAILY_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getHourlyRate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getDailyRate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VehicleTypeRecord
	 */
	public VehicleTypeRecord() {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE);
	}

	/**
	 * Create a detached, initialised VehicleTypeRecord
	 */
	public VehicleTypeRecord(java.lang.Integer id, java.lang.String uid, java.lang.String name, java.lang.Double hourlyRate, java.lang.Double dailyRate) {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.VehicleType.VEHICLE_TYPE);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, name);
		setValue(3, hourlyRate);
		setValue(4, dailyRate);
	}
}
