/**
 * This class is generated by jOOQ
 */
package edu.uga.csci4050.group3.jooq.rentalservice.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleRecord extends org.jooq.impl.UpdatableRecordImpl<edu.uga.csci4050.group3.jooq.rentalservice.tables.records.VehicleRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 709163367;

	/**
	 * Setter for <code>rentalservice.VEHICLE.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.uid</code>. 
	 */
	public void setUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.uid</code>. 
	 */
	public java.lang.String getUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.type</code>. 
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.type</code>. 
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.make</code>. 
	 */
	public void setMake(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.make</code>. 
	 */
	public java.lang.String getMake() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.model</code>. 
	 */
	public void setModel(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.model</code>. 
	 */
	public java.lang.String getModel() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.year</code>. 
	 */
	public void setYear(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.year</code>. 
	 */
	public java.lang.Integer getYear() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.mileage</code>. 
	 */
	public void setMileage(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.mileage</code>. 
	 */
	public java.lang.Integer getMileage() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.tag</code>. 
	 */
	public void setTag(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.tag</code>. 
	 */
	public java.lang.String getTag() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.lastservice</code>. 
	 */
	public void setLastservice(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.lastservice</code>. 
	 */
	public java.lang.Integer getLastservice() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>rentalservice.VEHICLE.location</code>. 
	 */
	public void setLocation(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>rentalservice.VEHICLE.location</code>. 
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.MAKE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.MILEAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.LASTSERVICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMake();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getMileage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getLastservice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getLocation();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VehicleRecord
	 */
	public VehicleRecord() {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE);
	}

	/**
	 * Create a detached, initialised VehicleRecord
	 */
	public VehicleRecord(java.lang.Integer id, java.lang.String uid, java.lang.String type, java.lang.String make, java.lang.String model, java.lang.Integer year, java.lang.Integer mileage, java.lang.String tag, java.lang.Integer lastservice, java.lang.String location) {
		super(edu.uga.csci4050.group3.jooq.rentalservice.tables.Vehicle.VEHICLE);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, type);
		setValue(3, make);
		setValue(4, model);
		setValue(5, year);
		setValue(6, mileage);
		setValue(7, tag);
		setValue(8, lastservice);
		setValue(9, location);
	}
}
